#%RAML 1.0
title: CalculatorAPI

/service1:
  get:
    description: Multiplies the input with two and sends the result to service2 
    queryParameters:
      num:
        displayName: Number
        type: integer
        description: Number of calculation
        example: 42
        required: true
    responses:
      200:
        body:
          text/plain:
            example: 144
/service2:
  get:
    description: Multiplicate input with three and then sends the result to service3 
    queryParameters:
      num:
        displayName: Number
        type: integer
        description: Number of calculation
        example: 42
        required: true
    responses:
      200:
        body:
          text/plain:
            example: 44
/service3:
  post:
    description: Multiplies the input with five 
    queryParameters:
      num:
        displayName: Number
        type: integer
        description: Number of calculation
        example: 42
        required: true
    responses:
      200:
        body:
          text/plain:
            example: 32
