#%RAML 1.0
title: CalculatorAPI

/start:
  post:
    description: Create a multiplications job
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "result": 44,
                "success": true,
                "status": 200
             }
    body:
      application/json:
        type: |
          {
            "type": "object",
            "$schema": "http://json-schema.org/draft-03/schema",
            "id": "http://jsonschema.net",
            "required": true,
            "properties": {
              "calculate": {
                "type": "integer",
                "required": true,
                "minimum": -128,
                "maximum": 127,
                "format": int8
              },
            },
          }
        example:
          {
            "calculate": 42,
          }
/calc1:
  post:
    description: Create a multiplications job
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "result": 44,
                "success": true,
                "status": 200
             }
    body:
      application/json:
        type: |
          {
            "type": "object",
            "$schema": "http://json-schema.org/draft-03/schema",
            "id": "http://jsonschema.net",
            "required": true,
            "properties": {
              "calculate": {
                "type": "integer",
                "required": true,
                "minimum": -128,
                "maximum": 127,
                "format": int8
              },
            },
          }
        example:
          {
            "calculate": 42,
          }
/calc2:
  post:
    description: Create a multiplications job
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "result": 44,
                "success": true,
                "status": 200
             }
    body:
      application/json:
        type: |
          {
            "type": "object",
            "$schema": "http://json-schema.org/draft-03/schema",
            "id": "http://jsonschema.net",
            "required": true,
            "properties": {
              "calculate": {
                "type": "integer",
                "required": true,
                "minimum": -128,
                "maximum": 127,
                "format": int8
              },
            },
          }
        example:
          {
            "calculate": 42,
          }

