[package]
name = "webhook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.15"
serde = "1"
serde_json = "1"
chrono = { version = "0.4", features = [ "serde" ] }
